### ISSUE TITLE
Problem with display of multivolume editions continues in this update

### ISSUE THREAD

**Issue by AlisonBabeu** [PerseusDL/catalog_data#73] opened 2016-01-14 20:44 UTC
The new multivolume modsCollection files are continuing to have some display issues in that all of the information for the first mods record in each collection still displays all of the information for whatever the final MODS record is in the collection. mods1 in each collection will display only the correct Alternate title while all of the other information will be a duplicate of the final mods record in the collection, mods4, etc.

This issue can be seen in this multivolume edition records for this edition of Athenaeus:
http://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0008.tlg001.opp-grc6.
The alternate title is correct for mods1, but the rest of the information is incorrect and duplicates the info of mods7, the final record. All of the information for all of the mods records other than the first is correct!

A related question/issues regards what title is chosen to display for the entire edition in the work results search page. For the work above, the edition title that displays in the online catalog, is "Deipnosophistae, The, Deipnosophists, Volume VII", the default title for the new modsCollection file seems to be the alternate title and or hostTitle for whatever the last mods file is in the modsCollection file.

**Comment by AlisonBabeu** [comment] 2016-01-14 20:45
Seems likely related to this issue documented here:
https://github.com/PerseusDL/perseus_catalog/issues/53

**Comment by AlisonBabeu** [comment] 2016-01-19 20:11
I've recently discovered another interesting error that seems to be occurring with these files, it appears that for all of the modsCollection files ingested in the last update, it created two modsCollection records within Github catalog_data. For example, a new German edition by [Thucydides](https://github.com/PerseusDL/catalog_data/tree/72a72700a1384cc69c6576595772aa4a57608eee/mods/greekLit/tlg0003/tlg001/opp-ger4) and a new edition of (Homer)[https://github.com/PerseusDL/catalog_data/blob/master/mods/greekLit/tlg0012/tlg002/opp-grc3/tlg0012.tlg002.opp-grc3.mods1.xml] and the edition of [Athenaeus](https://github.com/PerseusDL/catalog_data/tree/72a72700a1384cc69c6576595772aa4a57608eee/mods/greekLit/tlg0008/tlg001/opp-grc6) referenced above. Each of these directories have mods1 and mods2 files with the mods2 being a complete duplicate of the first. I did a few diffs to make sure but in each case the two mods files are exact duplicates of each other. 

I don't know if thathas anything to do with the indexing and display issues we're currently having.

**Comment by AlisonBabeu** [comment] 2016-01-19 20:31
Interestingly, there were two initial test multivolume modsCollection editions ingested with the July update [tlg0012.tlg001.opp-grc5](https://github.com/PerseusDL/catalog_data/blob/8d24ea906e9893720060b5ad3dafbe0efed8b778/mods/greekLit/tlg0012/tlg001/opp-grc5/tlg0012.tlg001.opp-grc5.mods1.xml)  and [urn:cts:greekLit:tlg2018.tlg002.opp-eng1](https://github.com/PerseusDL/catalog_data/blob/8d24ea906e9893720060b5ad3dafbe0efed8b778/mods/greekLit/tlg2018/tlg002/opp-eng1/tlg2018.tlg002.opp-eng1.mods1.xml), both of which are displaying the correct metadata for each MODS record in the catalog, [here](http://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0012.tlg001.opp-grc5) and [here](http://catalog.perseus.org/catalog/urn:cts:greekLit:tlg2018.tlg002.opp-eng1). No duplicate MODS records were created in catalog_data for either edition as well. The plot thickens!

**Comment by balmas** [comment] 2016-03-28 22:59
I am not sure but I think the extra mods files might be from a prior partial or failed update run in the update environment that wasn't fully cleaned out. I thought I had made sure to start clean, but it's possible that I made an error.  I would suggest deleting the duplicate mods files and i will check this carefully on the next build.

**Comment by AlisonBabeu** [comment] 2016-03-28 23:13
I'll delete them as I find them or should I try to make a concerted effort to delete them before Wednesday?

**Comment by balmas** [comment] 2016-03-28 23:16
I think you could just delete them as you find them.  If I'm right about the cause it shouldn't be a wide-spread problem.

**Comment by AlisonBabeu** [comment] 2016-03-29 15:59
Actually it now appears after [searching within the entire Github catalog_data repository](https://github.com/PerseusDL/catalog_data/search?p=4&q=mods2.xml+in%3Apath&utf8=%E2%9C%93) that the problem is much more widespread  in that this did not just happen with multivolume editions. I had spent a little time last night deleting duplicate MODS records generated for multivolume records in Thucydides but then realized that lots of individual work records (for example, this Alcestis edition of [Euripides](https://github.com/PerseusDL/catalog_data/tree/72a72700a1384cc69c6576595772aa4a57608eee/mods/greekLit/tlg0006/tlg002/opp-grc3) also had duplicate MODS records created when they were first created for the January 16th update

Removing these records as I find them or essentially manually might be far more time consuming then I thought originally. I was wondering if there was a way to create a targeted list of mods2.xml records that were created by the last update and just deleting those because we don't want to delete any of the mods2.xml records created for Perseus editions.

**Comment by perseuscatalog** [comment] 2016-03-29 16:16
We can do that but if I'm understanding you correctly we wouldn't want to limit it to just the last update. I also think we need to add something to the build process to prevent this from happening in the future.

Sent from my Verizon Wireless 4G LTE Droid
On Mar 29, 2016 11:59 AM, Alison Babeu <notifications@github.com> wrote:

Actually it now appears after searching within the entire Github catalog_data repository<https://github.com/PerseusDL/catalog_data/search?p=4&q=mods2.xml+in%3Apath&utf8=%E2%9C%93> that the problem is much more widespread in that this did not just happen with multivolume editions. I had spent a little time last night deleting duplicate MODS records generated for multivolume records in Thucydides but then realized that lots of individual work records (for example, this Alcestis edition of Euripides<https://github.com/PerseusDL/catalog_data/tree/72a72700a1384cc69c6576595772aa4a57608eee/mods/greekLit/tlg0006/tlg002/opp-grc3> also had duplicate MODS records created when they were first created for the January 16th update

Removing these records as I find them or essentially manually might be far more time consuming then I thought originally. I was wondering if there was a way to create a targeted list of mods2.xml records that were created by the last update and just deleting those because we don't want to delete any of the mods2.xml records created for Perseus editions.

**Comment by AlisonBabeu** [comment] 2016-03-29 16:18
I had never noticed the problem before this update but that certaintly doesn't mean it hasn't happened, and yes we would definitely want the build process to not do this in the future!

**Comment by PerseidsDeployer** [comment] 2016-03-29 16:27
Sorry I misunderstood the comment.  I will see what I can do.

**Comment by balmas** [comment] 2016-03-29 16:28
(Apparently I'm trying to see how many different identities I can can comment on under this issue ;) )

**Comment by balmas** [comment] 2016-03-29 18:24
@AlisonBabeu I submitted a PR to remove the duplicates, but I think before I try to do another update, we should talk about how this is really supposed to work. I think there was possibly a disconnect here when Anna added support for the modsCollections. I thought that what the process was supposed to do was to accept modsCollections on input from catalog_pending, but then split those into individual mods files for loading into the catalog, because of the way the indexing happened in blacklight a mods file == a record to display.  I could very well have misunderstood what was required in blacklight, but I think it would be a good idea to get straight when we want multiple mods files for a version and when we just want a single modsCollection.  Assuming that blacklight DOESN'T need them (which may or may not be true) is there ever a valid reason to have multiple individual mods files for a single version vs. the modsCollection?

**Comment by AlisonBabeu** [comment] 2016-03-29 18:34
If I'm reading you right, although I don't entirely know what Blacklight needs, essentially we decided that modsCollection files would be used to represent all versions made up of multiple volumes with one MODS record for each volume in the version. Ideally and going forward there should never be multiple individual mods files for a single version, and right now in catalog_data I think we have the confusing situation where a number of Perseus editions have two MODS records for the same "version" where I manually created the second one for a Epidoc edition and then the ingest named the file ...mods2.xml. I don't think there are two many other examples of where we have multiple MODS records for a single version unless they were erroneously created during one of the updates.

**Comment by balmas** [comment] 2016-03-29 18:39
that's where the disconnect came in. I think the modsCollections were intended to be used so that you didn't have to create multiple mods files for multi-volumes, but that the update process was supposed to generate individual mods files for each mods file in the collection.  But what coded was a half-mixture of this that does the wrong thing.. it creates multiple mods files but they all contain the same data...

**Comment by AlisonBabeu** [comment] 2016-04-14 17:58
So far from looking at the various multivolume editions reference in this issue as well as ones in the current import it seems that this process may be working correctly now!

**Comment by balmas** [comment] 2016-04-18 18:39
Closing this then. Fixed data in https://github.com/PerseusDL/catalog_data/releases/tag/20160418

**Closed by balmas** 2016-04-18 18:39 UTC
